关于页面
Open-Source-Bazaar/Open-Source-Bazaar.github.io pull request #6
Opened 2022-03-04 16:46 UTC by stevending1st

Checklist（清单）:
- 关于页面

2022-03-04 18:20 UTC, TechQuery requested changes

2022-03-04 18:20 UTC, TechQuery commented on pages/_app.tsx
> +            </Nav.Link>
用数组迭代出来

2022-03-04 18:20 UTC, TechQuery commented on pages/_app.tsx
> +          </a> */}
可以宣传一下该脚手架引用的 [Idea React 开源组件库](https://github.com/idea2app/Idea-React)

2022-03-04 18:20 UTC, TechQuery commented on pages/about.tsx
> +            </span>
段落正文中用语义化的 `<strong />`、`<em />`

2022-03-04 18:20 UTC, TechQuery commented on pages/about.tsx
> +          </p>
若是大段静态文字，可以用 MarkDown 写好了，再 `import` MDX：https://nextjs.org/docs/advanced-features/using-mdx

2022-03-06 05:40 UTC, TechQuery requested changes

2022-03-06 05:40 UTC, TechQuery commented on pages/_document.js
> +          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"
升到最新版？

2022-03-06 05:40 UTC, TechQuery commented on pages/about.mdx
> +  <PageContent>
最好放到布局组件，让 Markdown 文件比较纯净。

2022-03-06 06:08 UTC, stevending1st commented on pages/about.mdx
> +  <PageContent>
> 最好放到布局组件，让 Markdown 文件比较纯净。

我昨天弄了很久，没弄好~

2022-03-06 06:16 UTC, stevending1st commented on pages/_document.js
> +          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"
```suggestion
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"
```

2022-03-06 08:17 UTC, TechQuery approved these changes

2022-03-06 08:17 UTC, merged