首页优化、添加参与页面
Open-Source-Bazaar/Open-Source-Bazaar.github.io pull request #8
Opened 2022-03-08 15:46 UTC by stevending1st

首页优化、添加参与页面

2022-03-08 16:15 UTC, TechQuery requested changes

2022-03-08 16:15 UTC, TechQuery commented on pages/index.tsx
> +                <span className="fw-bold">……</span>
直接在父元素写加粗 class 即可，无需多套一层（下同）

2022-03-09 12:40 UTC, stevending1st commented on pages/index.tsx
> +                <span className="fw-bold">……</span>
> 直接在父元素写加粗 class 即可，无需多套一层（下同）

只有部分加粗

2022-03-09 12:53 UTC, TechQuery approved these changes

2022-03-09 12:53 UTC, merged